### ISSUE TITLE
Modificar a rota da tela de consulta de acessórios para ser a rota principal da aplicação

### ISSUE THREAD

**Issue by waltercoan** [FabricadeSoftwareUNIVILLE/ProjCOLABAssistant#15]
@Controller
@RequestMapping("/catalogo")
public class ConsultAccessoriesController {

modificar para
@Controller
@RequestMapping("/")
public class ConsultAccessoriesController {

**Comment by Georgia-Spirandeli** [comment]
Correção Aplicada
