### ISSUE TITLE
Tela de consulta de acessórios deve repetir um acessório para cada cor cadastrada no sistema

### ISSUE THREAD

**Issue by waltercoan** [FabricadeSoftwareUNIVILLE/ProjCOLABAssistant#17]
accessoryList.html

Sugestão:
<div class="container">
        	<div class="row" th:each="umacessorio : ${listAccessory}">
	        	<div class="card col-md-3" th:each="umacor : ${umacessorio.colorList}">
	  				<img class="card-img-top" src="/image/item.png" alt="Card image cap">
	  				<div class="card-body">
	    				<h5 class="card-title" th:text="${umacessorio.name}"></h5>
	    				<p class="card-text" th:text="${umacessorio.description}"></p>
	    				<a href="#" class="btn btn-primary">Mais</a>
	  				</div>
				</div>
        	</div>
        </div>

Além disso, propor uma alteração no diagrama de domínio, pois existe a necessidade de vínculo entre a cor e a foto do acessório na cor correta.

**Comment by waltercoan** [comment]
`<div class="container">
        	<div class="row" th:each="umacessorio : ${listAccessory}">
	        	<div class="card col-md-3" th:each="umacor : ${umacessorio.colorList}">
	  				<img class="card-img-top" src="/image/item.png" alt="Card image cap">
	  				<div class="card-body">
	    				<h5 class="card-title" th:text="${umacessorio.name}"></h5>
	    				<p class="card-text" th:text="${umacessorio.description}"></p>
	    				<a href="#" class="btn btn-primary">Mais</a>
	  				</div>
				</div>
        	</div>
        </div>`

**Comment by Georgia-Spirandeli** [comment]
Revisão Realizada
