### ISSUE TITLE
Incluir o cadastro de cores no menu do sistema - #35

### ISSUE THREAD

**Issue by waltercoan** [FabricadeSoftwareUNIVILLE/ProjCOLABAssistant#36]
A branch #35 criou o novo cadastro de cores mas não incluiu no menu do sistema, favor alterar o arquivo layout.html em uma nova branch para incluir o cadastro no menu.

**Comment by sabrinaboing** [comment]
Fixado na branch mantercores_sprint4_fix

**Comment by waltercoan** [comment]
OK
