### ISSUE TITLE
BUG: Cadastro de cores, quebrou o código do cadastro de categoria

### ISSUE THREAD

**Issue by waltercoan** [FabricadeSoftwareUNIVILLE/ProjCOLABAssistant#50]
Rever o código do cadastro de categoria, pois o cadastro de cores alterou o código do cadastro de categoria, não permitindo mais sua execução.

**Comment by waltercoan** [comment]
https://github.com/FabricadeSoftwareUNIVILLE/ProjCOLABAssistant/commit/164a1e1a7579f609ab34281b31c3bb74ab1f7215#diff-7771a1260489e0ec94718a06a00ffb10

**Comment by marcusmmoreira** [comment]
item corrigido na branch  correcaoinstendereco_sprint4
